services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: gameratings_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gameratings
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: gameratings_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
